apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranker-backend
  labels:
    layer: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      layer: ranker-backend
  template:
    metadata:
      labels:
        layer: ranker-backend
    spec:
      containers:
      - name: holdem-ranker
        image: chenchuk77/holdem-ranker:1.1
        
