kind: Service
apiVersion: v1
metadata:
  name: ranker-backend
  labels:
    app: ranker-app
spec:
  type: NodePort
  selector:
    layer: ranker-backend
  ports:
  - port: 3000
    nodePort: 32000
    
